# Generated by Django 4.2.10 on 2025-06-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
    ]
