# Generated by Django 4.2.10 on 2025-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
